### ISSUE TITLE
Suggestion: change the paragraph color to yellow

### ISSUE THREAD

**Issue by alexandre-psr** [alexandrepsr/practicing-github-actions-01#1]
Change the paragraph color to yellow.

```css
p {
  color: yellow;
}
```
